# Nombre de la aplicación
spring.application.name=autenticacioncuidapp

# 1. Configuración de la Base de Datos (MySQL en Laragon)
# El parámetro createDatabaseIfNotExist=true intentará crear la base de datos por ti
spring.datasource.url=jdbc:mysql://localhost:3306/cuidapp_auth?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
# En Laragon, por defecto la contraseña de root suele estar vacía. 
# Si le pusiste una, escríbela aquí.
spring.datasource.password=

# 2. Configuración de JPA / Hibernate
# 'update' creará las tablas (como 'users') automáticamente basándose en tu modelo Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Puerto del Microservicio
# Reservamos el 8080 para el API Gateway más adelante
server.port=8081

# 4. Configuración de JSON para compatibilidad con Flutter
#spring.jackson.serialization.write-dates-as-timestamps=false

# 5. JWT compartido con API Gateway
app.jwt.secret=${JWT_SECRET:esta_es_una_clave_muy_secreta_y_larga_para_cuidapp_2026}

