spring.application.name=catalogocuidapp

server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/cuidapp_catalog?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

upcitemdb.api.url=https://api.upcitemdb.com/prod/trial/lookup
