spring.application.name=medicamentoscuidapp


# 1. Configuración del Servidor
# Usamos el 8082 para no chocar con el de Autenticación (8081)
server.port=8082

# 2. Configuración de la Base de Datos (MySQL en Laragon)
# Usamos el truco para que cree la base de datos sola si no existe
spring.datasource.url=jdbc:mysql://localhost:3306/cuidapp_meds?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=

# 3. Configuración de JPA / Hibernate
# 'update' para que cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Hibernate detectará el dialecto de MySQL automáticamente, pero lo dejamos explícito
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. Configuración para carga de datos (Útil para el OCR)
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false